# 默认仿真参数配置
# AI Economist Simulation Configuration

# ==================== 税收政策 ====================
tax_policy:
  income_tax_rate: 0.225         # 个人所得税率 (0.0-1.0)
  vat_rate: 0.08                 # 增值税率 (0.0-1.0)
  corporate_tax_rate: 0.21      # 企业所得税率 (0.0-1.0)

# ==================== 劳动力市场 ====================
labor_market:
  dismissal_rate: 0.1            # 裁员率 (0.0-1.0)
  enable_dismissal: true         # 是否启用裁员机制
  unemployment_threshold: 0.4    # 失业率阈值 (0.0-1.0)
  enable_dynamic_job_posting: true  # 是否启用动态招聘
  first_month_job_rate: 0.9      # 第一个月发布工作比例 (0.0-1.0)
  job_posting_multiplier: 0.1    # 工作发布倍数

# ==================== 生产参数 ====================
production:
  labor_productivity_factor: 100.0   # 劳动生产率因子
  labor_elasticity: 0.7              # 劳动弹性 (0.0-1.0)
  profit_to_production_ratio: 0.7    # 利润转化为生产预算的比例 (0.0-1.0)
  min_production_per_product: 5.0    # 每个商品最小生产量
  
  # 已废弃参数（保留用于兼容）
  base_production_rate: 100.0        # [已废弃]基础生产率
  high_demand_multiplier: 1.5        # [已废弃]高需求商品补货倍数
  low_demand_multiplier: 0.7         # [已废弃]低需求商品补货倍数

# ==================== 市场参数 ====================
market:
  min_per_cat: 20                # 每类最少商品数
  multiplier: 12                 # 商品数量乘数（控制总商品数）
  price_adjustment_rate: 0.1     # 价格调整比例 (0.0-1.0)
  
  # 固有市场配置
  enable_inherent_market: true   # 是否启用固有市场
  inherent_market_consumption_rate: 0.65  # 固有市场每月消耗商品的比例 (0.0-1.0)
  inherent_market_focus_new_products: true  # 固有市场是否优先消耗新商品

# ==================== 系统规模 ====================
system_scale:
  num_households: 5              # 家庭数量
  num_iterations: 4              # 仿真迭代次数（月数）
  random_state: 42               # 随机种子

# ==================== 再分配政策 ====================
redistribution:
    redistribution_strategy: none  # 可选: "none", "equal", "income_proportional", "poverty_focused", "unemployment_focused", "family_size", "mixed"
    redistribution_poverty_weight: 0.3  
    redistribution_unemployment_weight: 0.2  
    redistribution_family_size_weight: 0.1  

# ==================== 性能参数 ====================
performance:
  max_concurrent_tasks: 300      # 最大并发任务数
  max_llm_concurrent: 600        # LLM最大并发数
  max_firm_concurrent: 50        # 企业最大并发数
  use_batch_budget_allocation: false  # 是否使用批量预算分配
  batch_size: 10                 # 批量处理的家庭数量
  batch_llm_timeout: 120         # 批量LLM请求超时时间（秒）

# ==================== 监控配置 ====================
monitoring:
  enable_monitoring: false       # 是否启用监控
  monitor_interval: 5.0          # 监控间隔（秒）

# ==================== 创新模块 ====================
innovation:
  enable_innovation_module: true        # 是否启用创新模块
  innovation_gamma: 1.2                 # 创新成功后的质量/产量阶梯 γ
  policy_encourage_innovation: true     # 政策是否鼓励创新
  innovation_lambda: 0.7               # 单位创新到达强度 λ
  innovation_concavity_beta: 0.6        # 研发有效劳动凹性 β (0<β≤1)
  innovation_research_share: 0.1        # 鼓励创新企业的研发投入比例（10%利润用于研发）

